version: "3"

services:
  anki:
    container_name: anki
    image: ghcr.io/diogovalentte/anki-docker:latest
    environment:
      - SYNC_USER1='username1:hashed_password'
      - SYNC_USER2='username2:hashed_password'
      - SYNC_USER3='username3:hashed_password'
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./data:/data
