services:
  anki-sync-server:
    container_name: anki-sync-server
    image: ghcr.io/diogovalentte/anki-sync-server:latest
    environment:
      - SYNC_USER1='username1:hashed_password'
      - SYNC_USER2='username2:hashed_password'
      - SYNC_USER3='username3:hashed_password'
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./sync_server_data:/data

  anki-desktop:
    container_name: anki-desktop
    image: ghcr.io/diogovalentte/anki-desktop:latest
    ports:
      - 3000:3000 # Web UI
      - 8765:8765 # AnkiConnect
    volumes:
      - ./desktop_data:/config/app/Anki2
    restart: unless-stopped

  anki-headless:
    container_name: anki-headless
    image: ghcr.io/diogovalentte/anki-headless:latest
    environment:
      - QT_QPA_PLATFORM=vnc # Can be "offscreen" too
      - ANKICONNECT_API_KEY=your_api_key_here # Optional, for AnkiConnect. If provided, configure your Yomichan, etc. to use this key.
    ports:
      # You can comment out the unprotected port if you want to use only the protected one, and vise versa.
      - 8765:8765 # Unprotected AnkiConnect
      - 8766:8766 # Protected AnkiConnect
    volumes:
      - ./headless_data:/data
    restart: unless-stopped
