version: "3"

services:
  anki:
    container_name: anki
    image: ghcr.io/diogovalentte/anki-docker:latest
    environment:
      - ANKI_USERNAME=
      - ANKI_PASSWORD=
      - NTFY_ADDRESS=
      - NTFY_TOPIC=
      - NTFY_TOKEN=
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
