name: Create and publish the anki sync server and desktop images

on:
  workflow_dispatch:
    inputs:
      anki_version_tag:
        description: "Tag for the Docker image (e.g., '1.0.0', '27.0')"
        required: true
      anki_connect_version_tag:
        description: "Tag for the Anki Connect Docker image (e.g., '1.0.0', '27.0')"
        required: true

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set image names
        run: |
          echo "SYNC_SERVER_IMAGE_NAME=${REGISTRY}/${{ github.repository_owner }}/anki-sync-server" >> $GITHUB_ENV
          echo "DESKTOP_IMAGE_NAME=${REGISTRY}/${{ github.repository_owner }}/anki-desktop" >> $GITHUB_ENV
          echo "HEADLESS_IMAGE_NAME=${REGISTRY}/${{ github.repository_owner }}/anki-headless" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for anki sync server
        id: sync-server-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.SYNC_SERVER_IMAGE_NAME }}

      - name: Extract metadata (tags, labels) for anki desktop
        id: desktop-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DESKTOP_IMAGE_NAME }}

      - name: Extract metadata (tags, labels) for anki headless
        id: headless-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.HEADLESS_IMAGE_NAME }}

      - name: Build and push anki sync server image
        uses: docker/build-push-action@v3
        with:
          context: sync_server
          file: sync_server/Dockerfile
          push: true
          provenance: false
          platforms: linux/amd64
          labels: ${{ steps.sync-server-meta.outputs.labels }}
          build-args: |
            ANKI_VERSION=${{ github.event.inputs.anki_version_tag }}
          tags: |
            ${{ env.SYNC_SERVER_IMAGE_NAME }}:latest
            ${{ env.SYNC_SERVER_IMAGE_NAME }}:${{ github.event.inputs.anki_version_tag }}

      - name: Build and push anki desktop image
        uses: docker/build-push-action@v3
        with:
          context: desktop
          file: desktop/Dockerfile
          push: true
          provenance: false
          platforms: linux/amd64
          labels: ${{ steps.desktop-meta.outputs.labels }}
          build-args: |
            ANKI_VERSION=${{ github.event.inputs.anki_version_tag }}
          tags: |
            ${{ env.DESKTOP_IMAGE_NAME }}:latest
            ${{ env.DESKTOP_IMAGE_NAME }}:${{ github.event.inputs.anki_version_tag }}

      - name: Build and push anki headless image
        uses: docker/build-push-action@v3
        with:
          context: headless
          file: headless/Dockerfile
          push: true
          provenance: false
          platforms: linux/amd64
          labels: ${{ steps.headless-meta.outputs.labels }}
          build-args: |
            ANKI_VERSION=${{ github.event.inputs.anki_version_tag }}
            ANKICONNECT_VERSION=${{ github.event.inputs.anki_connect_version_tag }}
          tags: |
            ${{ env.HEADLESS_IMAGE_NAME }}:latest
            ${{ env.HEADLESS_IMAGE_NAME }}:anki-${{ github.event.inputs.anki_version_tag }}
            ${{ env.HEADLESS_IMAGE_NAME }}:ankiconnect-${{ github.event.inputs.anki_connect_version_tag }}
